/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'v.louison' at '17/05/18 14:11' with Gradle 2.14.1
 *
 * @author v.louison, @date 17/05/18 14:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
